version: '3.9'
services:
    db:
        image: postgres:14.5-alpine
        container_name: postgresDB
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=prisma-psql-rest-api-dev
        volumes:
            - db-data:/var/lib/postgresql/data

    server:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile.dev
        image: prisma-psql-rest-api
        depends_on:
            - db
        volumes:
            - ../:/app
            - /app/node_modules
        env_file:
            - ../.env

    nginx:
        image: nginx:alpine
        volumes:
            - ../nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - server
        ports:
            - 5001:80

volumes:
    db-data:
