version: '3.9'
services:
    postgres:
        image: postgres:14.5-alpine
        container_name: postgres
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_DATA=${POSTGRES_DATA}
        ports:
            - ${HOST_PG_PORT}:5432
        volumes:
            - pg-data:/var/lib/postgresql/data

    server:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile.dev
        image: prisma-psql-rest-api
        depends_on:
            - postgres
        volumes:
            - ../:/app
            - /app/node_modules
        env_file:
            - ../.env
        ports:
            - ${HOST_SERVER_PORT}:5001
        links:
            - postgres

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        depends_on:
            - server
        ports:
            - ${HOST_PG_ADMIN_PORT}:80
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        volumes:
            - pgadmin-data:/var/lib/pgadmin

volumes:
    pg-data:
    pgadmin-data:
