version: '3.9'
services:
    db:
        image: postgres:14.5-alpine
        ports:
            - '5432:5432'
        env_file:
            - ../env
    server:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile.dev
        image: prisma-psql-rest-api
        depends_on:
            - db