FROM node:16.16.0-alpine

RUN yarn global add nodemon

WORKDIR /app

COPY ./package.json ./
COPY ./yarn.lock ./
COPY ./tsconfig.json ./
COPY ./prisma ./prisma

RUN yarn install --immutable --immutable-cache --check-cache

COPY ./ ./

EXPOSE 5001

CMD ["yarn", "run", "start:dev" ]