FROM node:16.16.0-alpine

RUN yarn global add nodemon

WORKDIR /app

COPY ./package.json ./
COPY ./yarn.lock ./
COPY ./tsconfig.json ./

RUN yarn install --immutable --immutable-cache --check-cache

COPY ./ ./

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

RUN /wait && npx prisma db push

EXPOSE 5001

CMD ["/wait", "&&", "yarn", "run", "start:dev" ]