version: '3.9'
services:
    postgres:
        image: postgres:14.5-alpine
        container_name: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=postsDB
            - POSTGRES_DATA=/var/lib/postgresql/data
        ports:
            - 5432:5432
        volumes:
            - pg-data:/var/lib/postgresql/data

    server:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile.dev
        image: prisma-psql-rest-api
        depends_on:
            - postgres
        volumes:
            - ../:/app
            - /app/node_modules
        env_file:
            - ../.env
        ports:
            - 5001:5001
        links:
            - postgres

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        depends_on:
            - server
        ports:
            - 8080:80
        environment:
            PGADMIN_DEFAULT_EMAIL: root@root.com
            PGADMIN_DEFAULT_PASSWORD: root
        volumes:
            - pgadmin-data:/var/lib/pgadmin

    # prisma-studio:
    #     container_name: prisma-studio
    #     image: timothyjmiller/prisma-studio:latest
    #     depends_on:
    #         - postgres
    #     env_file:
    #         - ../.env
    #     ports:
    #         - 5555:5555

volumes:
    pg-data:
    pgadmin-data:
