FROM node:16.16.0-alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./yarn.lock ./yarn.lock

RUN yarn install --immutable --immutable-cache --check-cache

COPY ./ ./

RUN yarn run build
RUN npx prisma migrate deploy

EXPOSE 5001

CMD [ "yarn", "run", "start:pro" ]